title: 'AWS クラウドプラクティショナー'
summary: '本書は自己研鑽のアウトプットする成果物を目的に執筆しております。'
topics: ['aws', '初心者向け'] # トピック（5つまで）
published: true # falseだと下書き
price: 500 # 有料の場合200〜5000
chapters:
  - free-index # はじめに
  - free-001
  - free-002
  - free-003
  - free-004
  - cost-tip
