title: 'AWS クラウドプラクティショナー'
summary: '
2024/01月から`AWS クラウドプラクティショナー`の学習を開始しました。
アウトプットとして本書を作成します。
他の人にも活用できたら幸いです。
随時記事を更新します。'
topics: ['aws', '初心者向け'] # トピック（5つまで）
published: true # falseだと下書き
price: 500 # 有料の場合200〜5000
chapters:
  - free-001
  - free-002
  - free-003
  - free-004
  - free-005
  - free-006
  - free-007
  - cost-tip
