title: '[Storybook] 私なりのまとめ'
summary: "Storybook公式サイトのチュートリアル\n▶ https://storybook.js.org/tutorials/intro-to-storybook/react/ja/get-started/ \nを参考に、Next.js + Tailwind CSS + TypeScript の構成でStorybookを動かし、GitHub Pagesへの公開とブランチごとの公開までを解説します。\n実際に動かして学んだことをアウトプットしたものです。"
topics: ['tailwindcss', 'nextjs', 'ts', 'storybook', '初心者向け'] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - chapter01
  - chapter02
  - chapter03
  - chapter04



