name: textlint

on:
  pull_request:
    paths:
      - 'articles/**/*.md'
      - 'books/**/*.md'
      - 'package.json'
      - 'package-lock.json'
  - '.github/workflows/ci_textlint.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed markdown files
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            articles/**/*.md
            books/**/*.md

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run textlint on changed files
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed.outputs.all_changed_files }}"
          npx --no-install textlint ${{ steps.changed.outputs.all_changed_files }}

      - name: No matching changes, skip lint
        if: steps.changed.outputs.any_changed != 'true'
        run: echo "No changes in articles/** or books/** markdown files."
